apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-web
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-web
  template:
    metadata:
      labels:
        app: manager-web
    spec:
      containers:
      - name: manager-web
        image: israa23/task-manager-web:6429898
        ports:
        - containerPort: 3000
