apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: dev
type: Opaque
stringData:
  SUPABASE_URL: "https://elpeuilawjfvpqvzhqeq.supabase.co"
  SUPABASE_KEY: "votre-cle-api-supabase-ici"
